#pragma once
// Auto-generated by train_models.py (SRS Section 9.5)
// Feature order: hourOfDay, dayOfWeek, bayOccupied, recentAvgCurrent,
//                sessionElapsedMin, historicalArrivalRate

#include <math.h>

// ---- Arrival probability model (Logistic Regression, via m2cgen) ----
static inline float predictArrival_raw(float * input) {
    return -2.5702208633573655f + input[0] * 0.014535023822447292f + input[1] * -0.03338836344147623f + input[2] * 0.07621072179269836f + input[3] * -0.004608036420865503f + input[4] * 0.00018834468631595306f + input[5] * 4.7989358575523084f;
}

static inline float predictArrival(float hourOfDay, float dayOfWeek, float bayOccupied,
                                   float recentAvgCurrent, float sessionElapsedMin,
                                   float historicalArrivalRate) {
  float input[6] = { hourOfDay, dayOfWeek, bayOccupied, recentAvgCurrent,
                     sessionElapsedMin, historicalArrivalRate };
  float raw = predictArrival_raw(input);
  return 1.0f / (1.0f + expf(-raw));  // Sigmoid -> probability 0..1
}

// ---- Session duration model (Decision Tree, via micromlgen) ----
namespace Eloquent {
    namespace ML {
        namespace Port {
            class DecisionTreeRegressor {
                public:
                    float predict(float *x) {
                        if (x[4] <= 103.85000228881836f) {
                            if (x[4] <= 52.95000076293945f) {
                                if (x[4] <= 26.050000190734863f) {
                                    if (x[4] <= 12.050000190734863f) {
                                        if (x[4] <= 3.0f) {
                                            return 211.82727272727274f;
                                        } else {
                                            return 201.94307692307692f;
                                        }
                                    } else {
                                        if (x[4] <= 12.200000286102295f) {
                                            return 150.75f;
                                        } else {
                                            return 190.19608938547478f;
                                        }
                                    }
                                } else {
                                    if (x[4] <= 38.95000076293945f) {
                                        if (x[4] <= 26.15000057220459f) {
                                            return 94.0f;
                                        } else {
                                            return 177.20000000000002f;
                                        }
                                    } else {
                                        if (x[0] <= 17.5f) {
                                            return 167.29029850746275f;
                                        } else {
                                            return 156.65652173913043f;
                                        }
                                    }
                                }
                            } else {
                                if (x[4] <= 77.35000228881836f) {
                                    if (x[4] <= 62.35000038146973f) {
                                        if (x[4] <= 53.25f) {
                                            return 84.95f;
                                        } else {
                                            return 152.81834862385318f;
                                        }
                                    } else {
                                        if (x[3] <= 13.154999732971191f) {
                                            return 137.94152542372888f;
                                        } else {
                                            return 143.47926829268292f;
                                        }
                                    }
                                } else {
                                    if (x[4] <= 88.75f) {
                                        if (x[0] <= 18.5f) {
                                            return 126.8052631578947f;
                                        } else {
                                            return 111.8730769230769f;
                                        }
                                    } else {
                                        if (x[4] <= 88.85000228881836f) {
                                            return 30.9f;
                                        } else {
                                            return 114.21442307692313f;
                                        }
                                    }
                                }
                            }
                        } else {
                            if (x[4] <= 162.0500030517578f) {
                                if (x[4] <= 129.0500030517578f) {
                                    if (x[4] <= 113.75f) {
                                        if (x[4] <= 104.5f) {
                                            return 81.2f;
                                        } else {
                                            return 104.17196969696967f;
                                        }
                                    } else {
                                        if (x[4] <= 114.10000228881836f) {
                                            return 52.125f;
                                        } else {
                                            return 88.16666666666663f;
                                        }
                                    }
                                } else {
                                    if (x[4] <= 147.6500015258789f) {
                                        if (x[5] <= 0.02350000012665987f) {
                                            return 53.411111111111104f;
                                        } else {
                                            return 76.348132780083f;
                                        }
                                    } else {
                                        if (x[3] <= 16.899999618530273f) {
                                            return 60.31129943502826f;
                                        } else {
                                            return 41.61999999999999f;
                                        }
                                    }
                                }
                            } else {
                                if (x[4] <= 190.0500030517578f) {
                                    if (x[4] <= 175.25f) {
                                        if (x[4] <= 170.5f) {
                                            return 51.557142857142864f;
                                        } else {
                                            return 46.41232876712329f;
                                        }
                                    } else {
                                        if (x[4] <= 183.1500015258789f) {
                                            return 39.282000000000004f;
                                        } else {
                                            return 32.21323529411764f;
                                        }
                                    }
                                } else {
                                    if (x[4] <= 206.79999542236328f) {
                                        if (x[4] <= 197.0f) {
                                            return 25.429411764705883f;
                                        } else {
                                            return 17.94903846153845f;
                                        }
                                    } else {
                                        if (x[4] <= 212.70000457763672f) {
                                            return 10.31714285714286f;
                                        } else {
                                            return 3.780645161290322f;
                                        }
                                    }
                                }
                            }
                        }
                    }
            };
        }
    }
}

static inline float predictDuration(float hourOfDay, float dayOfWeek, float bayOccupied,
                                    float recentAvgCurrent, float sessionElapsedMin,
                                    float historicalArrivalRate) {
  float input[6] = { hourOfDay, dayOfWeek, bayOccupied, recentAvgCurrent,
                     sessionElapsedMin, historicalArrivalRate };
  static Eloquent::ML::Port::DecisionTreeRegressor tree;
  return tree.predict(input);
}
